<?php

declare(strict_types=1);

namespace Celeris\Framework\Tooling\Generator;

/**
 * Implement controller generator behavior for the Tooling subsystem.
 *
 * It provides focused behavior for this type within the framework.
 * In practice, it is used by adjacent modules through explicit dependencies.
 */
final class ControllerGenerator implements GeneratorInterface
{
   /**
    * Handle name.
    *
    * @return string
    */
   public function name(): string
   {
      return 'controller';
   }

   /**
    * Handle description.
    *
    * @return string
    */
   public function description(): string
   {
      return 'Generates controller base + user wrapper classes with selectable routing style (safe regeneration).';
   }

   /**
    * @return array<int, GeneratedFileDraft>
    */
   public function generate(GenerationRequest $request): array
   {
      $module = $this->studly($request->module());
      $name = $this->studly($request->name());
      $className = str_ends_with($name, 'Controller') ? $name : $name . 'Controller';
      $baseClassName = $className . 'Base';
      $methodName = 'index';

      $routePrefix = trim((string) $request->option('route_prefix', '/' . strtolower($name)), '/');
      $routePath = '/' . ($routePrefix !== '' ? $routePrefix : strtolower($name));
      $routingType = strtolower(trim((string) $request->option('routing_type', 'attribute')));
      $routingType = $routingType === 'php' ? 'php' : 'attribute';

      $namespaceRoot = trim($request->namespaceRoot(), '\\');
      $namespace = $namespaceRoot . '\\' . $module . '\\Controller';
      $baseNamespace = $namespace . '\\Base';
      $basePath = 'src/' . $module . '/Controller/Base/' . $baseClassName . '.php';
      $path = 'src/' . $module . '/Controller/' . $className . '.php';
      $routesNamespace = $namespaceRoot . '\\' . $module . '\\Routes';
      $routesBaseNamespace = $routesNamespace . '\\Base';
      $resourceName = preg_replace('/Controller$/', '', $className) ?: $className;
      $routeRegistrarName = $resourceName . 'Routes';
      $routeRegistrarBaseName = $routeRegistrarName . 'Base';
      $routesBasePath = 'src/' . $module . '/Routes/Base/' . $routeRegistrarBaseName . '.php';
      $routesPath = 'src/' . $module . '/Routes/' . $routeRegistrarName . '.php';

      $baseContents = $routingType === 'attribute'
         ? <<<PHP
<?php

declare(strict_types=1);

namespace {$baseNamespace};

use Celeris\Framework\Http\Request;
use Celeris\Framework\Http\RequestContext;
use Celeris\Framework\Http\Response;
use Celeris\Framework\Routing\Attribute\Route;

/**
 * @generated by Celeris Tooling. Do not edit this file directly.
 * Place custom logic in {$namespace}\\{$className}.
 */
class {$baseClassName}
{
   #[Route(methods: ['GET'], path: '{$routePath}', summary: '{$name} endpoint')]
   public function {$methodName}(RequestContext \$ctx, Request \$request): Response
   {
      return new Response(200, ['content-type' => 'application/json; charset=utf-8'], '{"ok":true}');
   }
}
PHP
         : <<<PHP
<?php

declare(strict_types=1);

namespace {$baseNamespace};

use Celeris\Framework\Http\Request;
use Celeris\Framework\Http\RequestContext;
use Celeris\Framework\Http\Response;

/**
 * @generated by Celeris Tooling. Do not edit this file directly.
 * Place custom logic in {$namespace}\\{$className}.
 */
class {$baseClassName}
{
   public function {$methodName}(RequestContext \$ctx, Request \$request): Response
   {
      return new Response(200, ['content-type' => 'application/json; charset=utf-8'], '{"ok":true}');
   }
}
PHP;

      $contents = <<<PHP
<?php

declare(strict_types=1);

namespace {$namespace};

use {$baseNamespace}\\{$baseClassName};

final class {$className} extends {$baseClassName}
{
}
PHP;

      $drafts = [new GeneratedFileDraft($basePath, $baseContents . "\n")];

      $absolutePath = $request->basePath() . '/' . $path;
      if (!is_file($absolutePath)) {
         $drafts[] = new GeneratedFileDraft($path, $contents . "\n");
      }

      if ($routingType === 'php') {
         $routesBaseContents = <<<PHP
<?php

declare(strict_types=1);

namespace {$routesBaseNamespace};

use {$namespace}\\{$className};
use Celeris\Framework\Routing\RouteCollector;

/**
 * @generated by Celeris Tooling. Do not edit this file directly.
 * Register from bootstrap: {$routesNamespace}\\{$routeRegistrarName}::register(\$kernel->routes());
 */
class {$routeRegistrarBaseName}
{
   public static function register(RouteCollector \$routes): void
   {
      \$routes
         ->controller({$className}::class)
         ->get('{$routePath}', '{$methodName}');
   }
}
PHP;
         $drafts[] = new GeneratedFileDraft($routesBasePath, $routesBaseContents . "\n");

         $routesContents = <<<PHP
<?php

declare(strict_types=1);

namespace {$routesNamespace};

use {$routesBaseNamespace}\\{$routeRegistrarBaseName};

final class {$routeRegistrarName} extends {$routeRegistrarBaseName}
{
}
PHP;
         $absoluteRoutesPath = $request->basePath() . '/' . $routesPath;
         if (!is_file($absoluteRoutesPath)) {
            $drafts[] = new GeneratedFileDraft($routesPath, $routesContents . "\n");
         }
      }

      return $drafts;
   }

   /**
    * Handle studly.
    *
    * @param string $value
    * @return string
    */
   private function studly(string $value): string
   {
      $clean = preg_replace('/[^A-Za-z0-9]+/', ' ', $value) ?? '';
      $parts = array_filter(explode(' ', trim($clean)), static fn (string $part): bool => $part !== '');
      $studly = implode('', array_map(static fn (string $part): string => ucfirst($part), $parts));
      return $studly !== '' ? $studly : 'Generated';
   }
}
