<?php

declare(strict_types=1);

namespace Celeris\Framework\Tooling\Generator;

/**
 * Purpose: implement module generator behavior for the Tooling subsystem.
 * How: encapsulates its responsibilities behind explicit methods and typed dependencies.
 * Used in framework: invoked by tooling components when module generator functionality is required.
 */
final class ModuleGenerator implements GeneratorInterface
{
   /**
    * Handle name.
    *
    * @return string
    */
   public function name(): string
   {
      return 'module';
   }

   /**
    * Handle description.
    *
    * @return string
    */
   public function description(): string
   {
      return 'Generates a composable module with Base classes plus user wrappers for safe regeneration.';
   }

   /**
    * @return array<int, GeneratedFileDraft>
    */
   public function generate(GenerationRequest $request): array
   {
      $module = $this->studly($request->name());
      $namespaceRoot = trim($request->namespaceRoot(), '\\');

      $providerClass = $module . 'ServiceProvider';
      $providerBaseClass = $providerClass . 'Base';
      $providerNamespace = $namespaceRoot . '\\' . $module;
      $providerBaseNamespace = $providerNamespace . '\\Base';

      $providerPath = 'src/' . $module . '/' . $providerClass . '.php';
      $providerBasePath = 'src/' . $module . '/Base/' . $providerBaseClass . '.php';
      $providerBaseContents = <<<PHP
<?php

declare(strict_types=1);

namespace {$providerBaseNamespace};

use Celeris\Framework\Container\ServiceProviderInterface;
use Celeris\Framework\Container\ServiceRegistry;

/**
 * @generated by Celeris Tooling. Do not edit this file directly.
 * Place custom logic in {$providerNamespace}\\{$providerClass}.
 */
class {$providerBaseClass} implements ServiceProviderInterface
{
   public function register(ServiceRegistry \$services): void
   {
      // Register module services here.
   }
}
PHP;

      $providerContents = <<<PHP
<?php

declare(strict_types=1);

namespace {$providerNamespace};

use {$providerBaseNamespace}\\{$providerBaseClass};

final class {$providerClass} extends {$providerBaseClass}
{
}
PHP;

      $controllerClass = $module . 'HealthController';
      $controllerBaseClass = $controllerClass . 'Base';
      $controllerPath = 'src/' . $module . '/Controller/' . $controllerClass . '.php';
      $controllerBasePath = 'src/' . $module . '/Controller/Base/' . $controllerBaseClass . '.php';
      $controllerNamespace = $namespaceRoot . '\\' . $module . '\\Controller';
      $controllerBaseNamespace = $controllerNamespace . '\\Base';
      $routePath = '/' . strtolower($module) . '/health';
      $controllerBaseContents = <<<PHP
<?php

declare(strict_types=1);

namespace {$controllerBaseNamespace};

use Celeris\Framework\Http\Request;
use Celeris\Framework\Http\RequestContext;
use Celeris\Framework\Http\Response;
use Celeris\Framework\Routing\Attribute\Route;

/**
 * @generated by Celeris Tooling. Do not edit this file directly.
 * Place custom logic in {$controllerNamespace}\\{$controllerClass}.
 */
class {$controllerBaseClass}
{
   #[Route(methods: ['GET'], path: '{$routePath}', summary: '{$module} health check')]
   public function __invoke(RequestContext \$ctx, Request \$request): Response
   {
      return new Response(200, ['content-type' => 'application/json; charset=utf-8'], '{"module":"{$module}","status":"ok"}');
   }
}
PHP;

      $controllerContents = <<<PHP
<?php

declare(strict_types=1);

namespace {$controllerNamespace};

use {$controllerBaseNamespace}\\{$controllerBaseClass};

final class {$controllerClass} extends {$controllerBaseClass}
{
}
PHP;

      $drafts = [
         new GeneratedFileDraft($providerBasePath, $providerBaseContents . "\n"),
         new GeneratedFileDraft($controllerBasePath, $controllerBaseContents . "\n"),
      ];

      if (!is_file($request->basePath() . '/' . $providerPath)) {
         $drafts[] = new GeneratedFileDraft($providerPath, $providerContents . "\n");
      }

      if (!is_file($request->basePath() . '/' . $controllerPath)) {
         $drafts[] = new GeneratedFileDraft($controllerPath, $controllerContents . "\n");
      }

      return $drafts;
   }

   /**
    * Handle studly.
    *
    * @param string $value
    * @return string
    */
   private function studly(string $value): string
   {
      $clean = preg_replace('/[^A-Za-z0-9]+/', ' ', $value) ?? '';
      $parts = array_filter(explode(' ', trim($clean)), static fn (string $part): bool => $part !== '');
      $studly = implode('', array_map(static fn (string $part): string => ucfirst($part), $parts));
      return $studly !== '' ? $studly : 'Module';
   }
}

